api_caller/urls.py
from django.urls import path
from . import views

app_name = 'api_caller'

urlpatterns = [
    path('', views.test_api, name='test_api'),
    path('wiki_api', views.wiki_api, name='wiki_api'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('api_caller.urls')),
    path('admin/', admin.site.urls),
]

api_caller/models.py
from django.db import models

# Create your models here.

api_caller/views.py
import json
import requests as req_pkg

from django.http import JsonResponse
from django.shortcuts import render


def test_api(request):
    return render(request, 'test_api.html')


def wiki_api(request):
    url = 'https://en.wikipedia.org/w/api.php'
    # data = {
    #     "titles": request.GET.get('word'),
    #     "action": "query",
    #     "prop": "images",
    #     "format": "json"
    # }
    data = {
        "titles": request.GET.get('word'),
        "action": "query",
        "prop": "pageimages",
        "pithumbsize": 500,
        "format": "json",
    }
    img = None
    # rop=&format=json&pithumbsize=100
    r = req_pkg.get(url, params=data)
    r_data = json.loads(r.text)
    r_pages = r_data.get('query', {}).get('pages')
    if r_pages:
        for key, img_parent in r_pages.items():
            img = img_parent.get("thumbnail", {}).get("source")
    # print(img)
    return JsonResponse({
        "img": img
    })

api_caller/templates/test_api.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<form>
    <input type="text" id="find-me">
    <button>search</button>
</form>

<img src="" alt="" id="result" style="display: none;">

<script src="{% static 'main/js/jquery-3.3.1.min.js' %}"></script>


<script>
    (function ($) {
        $(document).ready(function () {
            $('button').click(function (e) {
                e.preventDefault();
                $.ajax({
                    url: '{% url 'api_caller:wiki_api' %}',
                    dataType: 'json',
                    method: "GET",
                    data: {
                        word: $('#find-me').val()
                    },
                    success: function (data) {
                        if(data.img)
                            $('#result').attr("src", data.img).show();
                        else
                            $('#result').attr("src", '')
                    }
                })
            })
        });
    })(jQuery)
</script>

</body>
</html>